/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.PersonaDAO;
import DTO.HotelDTO;
import Model.Cliente;
import Service.ServiceHotel;
import java.awt.Color;
import static java.awt.Event.DELETE;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.event.TableModelEvent.ALL_COLUMNS;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan Cruz
 */
public class GUIMain extends javax.swing.JFrame {

    /**
     * Creates new form GUIMain
     */
    public GUIMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgNoSeEncontroPersona = new javax.swing.JDialog();
        pnInicioSesion1 = new javax.swing.JPanel();
        tgTienesCuenta = new javax.swing.JLabel();
        btnSi = new javax.swing.JButton();
        btnNo = new javax.swing.JButton();
        pnInicioSesion2 = new javax.swing.JPanel();
        tgDniPresente = new javax.swing.JLabel();
        txtDniCheck = new javax.swing.JTextField();
        tgDniCheck = new javax.swing.JLabel();
        btnVerificarDni = new javax.swing.JButton();
        btnAtrasIS2 = new javax.swing.JButton();
        pnMenuCliente = new javax.swing.JPanel();
        btnSalirMenuCliente = new javax.swing.JButton();
        btnRealizarReserva = new javax.swing.JButton();
        pnMostrarHotelesCliente = new javax.swing.JPanel();
        tgSeleccionaHotel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoteles = new javax.swing.JTable();
        btnAtrasMostrarHoteles = new javax.swing.JButton();
        pnReserva = new javax.swing.JPanel();
        tgSeleccionaHotel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAtrasReserva = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout dlgNoSeEncontroPersonaLayout = new javax.swing.GroupLayout(dlgNoSeEncontroPersona.getContentPane());
        dlgNoSeEncontroPersona.getContentPane().setLayout(dlgNoSeEncontroPersonaLayout);
        dlgNoSeEncontroPersonaLayout.setHorizontalGroup(
            dlgNoSeEncontroPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dlgNoSeEncontroPersonaLayout.setVerticalGroup(
            dlgNoSeEncontroPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnInicioSesion1.setBackground(new java.awt.Color(0, 255, 102));

        tgTienesCuenta.setFont(new java.awt.Font("Google Sans", 0, 24)); // NOI18N
        tgTienesCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tgTienesCuenta.setText("¿Ya tienes una cuenta?");

        btnSi.setText("Si");
        btnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiActionPerformed(evt);
            }
        });

        btnNo.setText("No");

        javax.swing.GroupLayout pnInicioSesion1Layout = new javax.swing.GroupLayout(pnInicioSesion1);
        pnInicioSesion1.setLayout(pnInicioSesion1Layout);
        pnInicioSesion1Layout.setHorizontalGroup(
            pnInicioSesion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tgTienesCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnInicioSesion1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(btnSi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                .addComponent(btnNo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
        );
        pnInicioSesion1Layout.setVerticalGroup(
            pnInicioSesion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInicioSesion1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(tgTienesCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addGroup(pnInicioSesion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(165, 165, 165))
        );

        pnInicioSesion2.setBackground(new java.awt.Color(255, 255, 0));

        tgDniPresente.setFont(new java.awt.Font("Google Sans", 0, 24)); // NOI18N
        tgDniPresente.setForeground(new java.awt.Color(0, 0, 0));
        tgDniPresente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tgDniPresente.setText("Ingrese su DNI para iniciar sesión");

        txtDniCheck.setText("11.111.111");
        txtDniCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniCheckActionPerformed(evt);
            }
        });

        tgDniCheck.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        tgDniCheck.setForeground(new java.awt.Color(0, 0, 0));
        tgDniCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tgDniCheck.setText("DNI:");

        btnVerificarDni.setText("Verificar");
        btnVerificarDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarDniActionPerformed(evt);
            }
        });

        btnAtrasIS2.setText("Atrás");
        btnAtrasIS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasIS2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnInicioSesion2Layout = new javax.swing.GroupLayout(pnInicioSesion2);
        pnInicioSesion2.setLayout(pnInicioSesion2Layout);
        pnInicioSesion2Layout.setHorizontalGroup(
            pnInicioSesion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tgDniPresente, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInicioSesion2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tgDniCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnInicioSesion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerificarDni)
                    .addComponent(txtDniCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(369, 369, 369))
            .addGroup(pnInicioSesion2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btnAtrasIS2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnInicioSesion2Layout.setVerticalGroup(
            pnInicioSesion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInicioSesion2Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(tgDniPresente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(pnInicioSesion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDniCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tgDniCheck))
                .addGap(60, 60, 60)
                .addComponent(btnVerificarDni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(btnAtrasIS2)
                .addGap(102, 102, 102))
        );

        pnMenuCliente.setBackground(new java.awt.Color(255, 51, 0));

        btnSalirMenuCliente.setText("Salir");
        btnSalirMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirMenuClienteActionPerformed(evt);
            }
        });

        btnRealizarReserva.setText("Hacer Reserva");
        btnRealizarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnMenuClienteLayout = new javax.swing.GroupLayout(pnMenuCliente);
        pnMenuCliente.setLayout(pnMenuClienteLayout);
        pnMenuClienteLayout.setHorizontalGroup(
            pnMenuClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuClienteLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnSalirMenuCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMenuClienteLayout.createSequentialGroup()
                .addContainerGap(324, Short.MAX_VALUE)
                .addComponent(btnRealizarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(312, 312, 312))
        );
        pnMenuClienteLayout.setVerticalGroup(
            pnMenuClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMenuClienteLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnRealizarReserva)
                .addGap(388, 388, 388)
                .addComponent(btnSalirMenuCliente)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pnMostrarHotelesCliente.setBackground(new java.awt.Color(0, 0, 255));

        tgSeleccionaHotel.setFont(new java.awt.Font("Google Sans", 0, 24)); // NOI18N
        tgSeleccionaHotel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tgSeleccionaHotel.setText("Selecciona el Hotel que deseas reservar!");

        tblHoteles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Estrellas", "Habitaciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoteles.setToolTipText("");
        tblHoteles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblHotelesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoteles);

        btnAtrasMostrarHoteles.setText("Atrás");

        javax.swing.GroupLayout pnMostrarHotelesClienteLayout = new javax.swing.GroupLayout(pnMostrarHotelesCliente);
        pnMostrarHotelesCliente.setLayout(pnMostrarHotelesClienteLayout);
        pnMostrarHotelesClienteLayout.setHorizontalGroup(
            pnMostrarHotelesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMostrarHotelesClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMostrarHotelesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                    .addComponent(tgSeleccionaHotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnMostrarHotelesClienteLayout.createSequentialGroup()
                        .addComponent(btnAtrasMostrarHoteles)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnMostrarHotelesClienteLayout.setVerticalGroup(
            pnMostrarHotelesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMostrarHotelesClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tgSeleccionaHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAtrasMostrarHoteles)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pnReserva.setBackground(new java.awt.Color(153, 0, 153));

        tgSeleccionaHotel1.setFont(new java.awt.Font("Google Sans", 0, 24)); // NOI18N
        tgSeleccionaHotel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tgSeleccionaHotel1.setText("Selecciona la habitación que deseas reservar!");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Habitación N°", "Cantidad de huespedes"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        btnAtrasReserva.setText("Atrás");

        javax.swing.GroupLayout pnReservaLayout = new javax.swing.GroupLayout(pnReserva);
        pnReserva.setLayout(pnReservaLayout);
        pnReservaLayout.setHorizontalGroup(
            pnReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tgSeleccionaHotel1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(pnReservaLayout.createSequentialGroup()
                        .addComponent(btnAtrasReserva)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnReservaLayout.setVerticalGroup(
            pnReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tgSeleccionaHotel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAtrasReserva)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnInicioSesion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(273, 273, 273)
                .addComponent(jButton3)
                .addGap(59, 59, 59))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnInicioSesion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnMenuCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnMostrarHotelesCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnInicioSesion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(22, 22, 22))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pnInicioSesion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 56, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pnMenuCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 56, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pnMostrarHotelesCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 56, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pnReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 56, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pnInicioSesion1.setVisible(true);
        pnInicioSesion2.setVisible(false);
        pnMenuCliente.setVisible(false);
        pnMostrarHotelesCliente.setVisible(false);
        pnReserva.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        pnInicioSesion1.setVisible(false);
        pnInicioSesion2.setVisible(true);
        pnMenuCliente.setVisible(false); 
        pnMostrarHotelesCliente.setVisible(false);
        pnReserva.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        pnInicioSesion1.setVisible(false);
        pnInicioSesion2.setVisible(false);
        pnMenuCliente.setVisible(true);
        pnMostrarHotelesCliente.setVisible(false);
        pnReserva.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
            
        pnInicioSesion1.setVisible(false);
        pnInicioSesion2.setVisible(true);
        pnMenuCliente.setVisible(false);
        pnMostrarHotelesCliente.setVisible(false);
        pnReserva.setVisible(false);
        
    }//GEN-LAST:event_btnSiActionPerformed

    private void txtDniCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniCheckActionPerformed

    private void btnVerificarDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarDniActionPerformed
        
        PersonaDAO persDAO = new PersonaDAO();
        String dni = txtDniCheck.getSelectedText();
         
         Cliente cliente = persDAO.obtenerClientePorDNI(dni);
         
         if (cliente == null){
             
             JOptionPane.showMessageDialog(this, "No se encontró una persona con ese DNI en la bd", "ERROR", JOptionPane.ERROR_MESSAGE);
             
         }
        
    }//GEN-LAST:event_btnVerificarDniActionPerformed

    private void btnSalirMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirMenuClienteActionPerformed

        pnInicioSesion1.setVisible(false);
        pnInicioSesion2.setVisible(true);
        pnMenuCliente.setVisible(false);
        pnMostrarHotelesCliente.setVisible(false);
        pnReserva.setVisible(false);
        
    }//GEN-LAST:event_btnSalirMenuClienteActionPerformed

    private void btnRealizarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarReservaActionPerformed
        
        pnInicioSesion1.setVisible(false);
        pnInicioSesion2.setVisible(false);
        pnMenuCliente.setVisible(false);
        pnMostrarHotelesCliente.setVisible(true);
        pnReserva.setVisible(false);
        
        List <HotelDTO> hoteles = serviceHotel.obtenerHoteles();
        
        DefaultTableModel tModel  = (DefaultTableModel)this.tblHoteles.getModel();
        
        tModel.setRowCount(0);
        
        for (HotelDTO hotel : hoteles){
            
            String nombre = hotel.getNombre();
            int estrellas = hotel.getEstrellas();
            int cantHabitaciones = hotel.getCantidadHabitaciones();
            
            Object [] objetoTabla = new Object []{nombre, estrellas, cantHabitaciones};
            
            tModel.addRow(objetoTabla);
            
        }
        
    }//GEN-LAST:event_btnRealizarReservaActionPerformed

    private void btnAtrasIS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasIS2ActionPerformed
        pnInicioSesion1.setVisible(true);
        pnInicioSesion2.setVisible(false);
        pnMenuCliente.setVisible(false);
        pnMostrarHotelesCliente.setVisible(false);
        pnReserva.setVisible(false);
    }//GEN-LAST:event_btnAtrasIS2ActionPerformed

    private void tblHotelesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHotelesMousePressed
        
        System.out.println(tblHoteles.getSelectedRow());
        
        System.out.println(tblHoteles.getValueAt(tblHoteles.getSelectedRow(), 0));
        
        pnInicioSesion1.setVisible(false);
        pnInicioSesion2.setVisible(false);
        pnMenuCliente.setVisible(false);
        pnMostrarHotelesCliente.setVisible(false);
        pnReserva.setVisible(true);
    }//GEN-LAST:event_tblHotelesMousePressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMain().setVisible(true);
            }
        });
        
    }

    private ServiceHotel serviceHotel = new ServiceHotel();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasIS2;
    private javax.swing.JButton btnAtrasMostrarHoteles;
    private javax.swing.JButton btnAtrasReserva;
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnRealizarReserva;
    private javax.swing.JButton btnSalirMenuCliente;
    private javax.swing.JButton btnSi;
    private javax.swing.JButton btnVerificarDni;
    private javax.swing.JDialog dlgNoSeEncontroPersona;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnInicioSesion1;
    private javax.swing.JPanel pnInicioSesion2;
    private javax.swing.JPanel pnMenuCliente;
    private javax.swing.JPanel pnMostrarHotelesCliente;
    private javax.swing.JPanel pnReserva;
    private javax.swing.JTable tblHoteles;
    private javax.swing.JLabel tgDniCheck;
    private javax.swing.JLabel tgDniPresente;
    private javax.swing.JLabel tgSeleccionaHotel;
    private javax.swing.JLabel tgSeleccionaHotel1;
    private javax.swing.JLabel tgTienesCuenta;
    private javax.swing.JTextField txtDniCheck;
    // End of variables declaration//GEN-END:variables
}
